import { Translations } from './types';

export const translations: Translations = {
  // Login Screen
  login_subtitle: {
    pt: 'Seu momento de brilhar. Crie seu portfólio de moda com IA.',
    it: 'Il tuo momento di brillare. Crea il tuo portfolio di moda con l\'IA.',
    en: 'Your moment to shine. Create your fashion portfolio with AI.'
  },
  login_button: {
    pt: 'Entrar com Google',
    it: 'Accedi con Google',
    en: 'Sign in with Google'
  },
  // Terms Screen
  terms_title: {
    pt: 'Termos de Serviço e Consentimento',
    it: 'Termini di Servizio e Consenso',
    en: 'Terms of Service and Consent'
  },
  terms_welcome: {
    pt: 'Bem-vindo(a) ao {0}!',
    it: 'Benvenuto/a in {0}!',
    en: 'Welcome to {0}!'
  },
  terms_intro: {
    pt: 'Ao usar nosso aplicativo, você concorda com os seguintes termos:',
    it: 'Utilizzando la nostra applicazione, accetti i seguenti termini:',
    en: 'By using our application, you agree to the following terms:'
  },
  terms_1_title: {
    pt: 'Gênero na Moda',
    it: 'Genere nella Moda',
    en: 'Gender in Fashion'
  },
  terms_1_text: {
    pt: 'Você entende que a moda é uma forma de arte e expressão. As imagens geradas podem apresentar estilos andróginos ou não convencionais. Os estilistas frequentemente vestem modelos masculinos com roupas que podem parecer femininas e vice-versa. O aplicativo refletirá essa diversidade criativa.',
    it: 'Comprendi che la moda è una forma d\'arte ed espressione. Le immagini generate possono presentare stili androgini o non convenzionali. Gli stilisti vestono spesso modelli maschili con abiti che possono sembrare femminili e viceversa. L\'applicazione rifletterà questa diversità creativa.',
    en: 'You understand that fashion is a form of art and expression. The generated images may feature androgynous or unconventional styles. Designers often dress male models in clothes that may appear feminine and vice versa. The application will reflect this creative diversity.'
  },
  terms_2_title: {
    pt: 'Exibição na Comunidade',
    it: 'Esposizione nella Community',
    en: 'Display in the Community'
  },
  terms_2_text: {
    pt: 'Você autoriza que as imagens geradas com seu rosto apareçam na seção "Comunidade" do aplicativo por um período de até 7 (sete) dias. Essas imagens serão visíveis para outros usuários da plataforma.',
    it: 'Autorizzi la visualizzazione delle immagini generate con il tuo volto nella sezione "Community" dell\'app per un periodo massimo di 7 (sette) giorni. Queste immagini saranno visibili agli altri utenti della piattaforma.',
    en: 'You authorize the images generated with your face to appear in the "Community" section of the app for a period of up to 7 (seven) days. These images will be visible to other users of the platform.'
  },
  terms_3_title: {
    pt: 'Compartilhamento Externo',
    it: 'Condivisione Esterna',
    en: 'External Sharing'
  },
  terms_3_text: {
    pt: 'As imagens na comunidade podem ser compartilhadas por outros usuários para fora do aplicativo {0}, através de links ou downloads. O {1} não se responsabiliza pelo uso de sua imagem fora da nossa plataforma.',
    it: 'Le immagini nella community possono essere condivise da altri utenti al di fuori dell\'app {0}, tramite link o download. {1} non è responsabile per l\'uso della tua immagine al di fuori della nostra piattaforma.',
    en: 'Images in the community can be shared by other users outside the {0} app, via links or downloads. {1} is not responsible for the use of your image outside our platform.'
  },
  terms_4_title: {
    pt: 'Uso de Dados e Imagens',
    it: 'Uso di Dati e Immagini',
    en: 'Use of Data and Images'
  },
  terms_4_text: {
    pt: 'Você concede ao {0} o direito de usar e armazenar, a nosso critério, todos os dados fornecidos (nome de usuário, cidade) e as imagens geradas por você na plataforma para fins de melhoria do serviço, marketing e operações internas.',
    it: 'Concedi a {0} il diritto di utilizzare e archiviare, a nostra discrezione, tutti i dati forniti (nome utente, città) e le immagini da te generate sulla piattaforma per scopi di miglioramento del servizio, marketing e operazioni interne.',
    en: 'You grant {0} the right to use and store, at our discretion, all data provided (username, city) and the images generated by you on the platform for service improvement, marketing, and internal operations.'
  },
  terms_5_title: {
    pt: 'Responsabilidade',
    it: 'Responsabilità',
    en: 'Responsibility'
  },
  terms_5_text: {
    pt: 'Use o aplicativo de forma responsável. Não envie imagens de terceiros sem consentimento ou conteúdo que seja ilegal ou ofensivo.',
    it: 'Usa l\'applicazione in modo responsabile. Non caricare immagini di terzi senza consenso o contenuti illegali od offensivi.',
    en: 'Use the application responsibly. Do not upload images of third parties without consent or content that is illegal or offensive.'
  },
  terms_checkbox_label: {
    pt: 'Eu li, entendi e concordo com os Termos de Serviço.',
    it: 'Ho letto, compreso e accetto i Termini di Servizio.',
    en: 'I have read, understood, and agree to the Terms of Service.'
  },
  terms_agree_button: {
    pt: 'Concordo e Continuar',
    it: 'Accetto e Continuo',
    en: 'Agree and Continue'
  },
  // Profile Setup
  profile_setup_title: {
    pt: 'Complete seu Perfil',
    it: 'Completa il tuo Profilo',
    en: 'Complete your Profile'
  },
  profile_setup_subtitle: {
    pt: 'Estamos quase prontos para sua estreia!',
    it: 'Siamo quasi pronti per il tuo debutto!',
    en: 'We are almost ready for your debut!'
  },
  profile_setup_language_label: {
    pt: 'Idioma do App',
    it: 'Lingua dell\'App',
    en: 'App Language'
  },
  profile_setup_country_label: {
    pt: 'País',
    it: 'Paese',
    en: 'Country'
  },
  profile_setup_country_placeholder: {
    pt: 'Digite seu país',
    it: 'Inserisci il tuo paese',
    en: 'Enter your country'
  },
  profile_setup_username_label: {
    pt: 'Nome de Usuário',
    it: 'Nome Utente',
    en: 'Username'
  },
  profile_setup_city_label: {
    pt: 'Sua Cidade',
    it: 'La tua Città',
    en: 'Your City'
  },
  profile_setup_city_placeholder: {
    pt: 'Ex: São Paulo',
    it: 'Es: Roma',
    en: 'Ex: New York'
  },
  profile_setup_continue_button: {
    pt: 'Continuar para a Selfie',
    it: 'Continua con il Selfie',
    en: 'Continue to Selfie'
  },
  // Selfie Capture
  selfie_capture_title: {
    pt: 'Capture sua Selfie',
    it: 'Scatta il tuo Selfie',
    en: 'Capture Your Selfie'
  },
  selfie_capture_subtitle: {
    pt: 'Posicione seu rosto no centro.',
    it: 'Posiziona il tuo viso al centro.',
    en: 'Position your face in the center.'
  },
  selfie_capture_retake_button: {
    pt: 'Tirar Outra',
    it: 'Scatta di Nuovo',
    en: 'Retake'
  },
  selfie_capture_confirm_button: {
    pt: 'Confirmar',
    it: 'Conferma',
    en: 'Confirm'
  },
  alert_camera_permission: {
    pt: 'Não foi possível acessar a câmera. Por favor, verifique as permissões no seu navegador.',
    it: 'Impossibile accedere alla fotocamera. Per favore, controlla i permessi nel tuo browser.',
    en: 'Could not access the camera. Please check the permissions in your browser.'
  },
  // Style Selector
  style_selector_title: {
    pt: 'Qual será o seu look?',
    it: 'Quale sarà il tuo look?',
    en: 'What will be your look?'
  },
  style_selector_subtitle: {
    pt: 'Descreva uma marca, um estilo, ou clique em uma das nossas sugestões.',
    it: 'Descrivi una marca, uno stile, o clicca su uno dei nostri suggerimenti.',
    en: 'Describe a brand, a style, or click on one of our suggestions.'
  },
  style_selector_placeholder: {
    pt: 'Ex: \'Estilo futurista da Balenciaga com óculos neon\'',
    it: 'Es: \'Stile futuristico di Balenciaga con occhiali neon\'',
    en: 'Ex: \'Futuristic Balenciaga style with neon glasses\''
  },
  style_selector_suggestions: {
    pt: 'Sugestões',
    it: 'Suggerimenti',
    en: 'Suggestions'
  },
  style_selector_generate_button: {
    pt: '✨ Aconteça a Mágica ✨',
    it: '✨ Che la Magia Abbia Inizio ✨',
    en: '✨ Let the Magic Happen ✨'
  },
  // Generating Screen
  generating_title: {
    pt: 'Gerando sua obra-prima...',
    it: 'Generando il tuo capolavoro...',
    en: 'Generating your masterpiece...'
  },
  generating_subtitle: {
    pt: 'A IA está criando seu portfólio. Isso pode levar um minuto.',
    it: 'L\'IA sta creando il tuo portfolio. Potrebbe volerci un minuto.',
    en: 'The AI is creating your portfolio. This might take a minute.'
  },
  generating_step1: { pt: 'Analisando traços da selfie...', it: 'Analizzando i tratti del selfie...', en: 'Analyzing selfie features...' },
  generating_step2: { pt: 'Esboçando 6 poses exclusivas...', it: 'Bozzando 6 pose esclusive...', en: 'Sketching 6 exclusive poses...' },
  generating_step3: { pt: 'Aplicando o estilo de moda selecionado...', it: 'Applicando lo stile di moda selezionato...', en: 'Applying selected fashion style...' },
  generating_step4: { pt: 'Ajustando iluminação e cenário...', it: 'Regolando illuminazione e scenario...', en: 'Adjusting lighting and scenery...' },
  generating_step5: { pt: 'Renderizando em alta definição...', it: 'Renderizzando in alta definizione...', en: 'Rendering in high definition...' },
  generating_step6: { pt: 'Adicionando a marca d\'água final...', it: 'Aggiungendo il watermark finale...', en: 'Adding the final watermark...' },
  generating_tip1: { pt: 'Dica de mestre: a confiança é o seu melhor acessório.', it: 'Consiglio da maestro: la fiducia è il tuo miglior accessorio.', en: 'Master tip: confidence is your best accessory.' },
  generating_tip2: { pt: 'A passarela espera por você...', it: 'La passerella ti aspetta...', en: 'The runway awaits you...' },
  generating_tip3: { pt: 'Preparando seu close-up...', it: 'Preparando il tuo primo piano...', en: 'Preparing your close-up...' },
  generating_tip4: { pt: 'Cada grande modelo começou com uma única foto.', it: 'Ogni grande modello ha iniziato con una singola foto.', en: 'Every great model started with a single photo.' },
  generating_tip5: { pt: 'Lembre-se: você é a estrela.', it: 'Ricorda: la stella sei tu.', en: 'Remember: you are the star.' },
  // Main View
  main_view_create_title: { pt: 'Criar nova imagem', it: 'Crea nuova immagine', en: 'Create new image' },
  main_view_step1: { pt: '1. Escolha um estilo', it: '1. Scegli uno stile', en: '1. Choose a style' },
  main_view_style_other: { pt: 'Outro', it: 'Altro', en: 'Other' },
  main_view_style_placeholder: { pt: 'Descreva seu estilo...', it: 'Descrivi il tuo stile...', en: 'Describe your style...' },
  main_view_step2: { pt: '2. Gere sua imagem', it: '2. Genera la tua immagine', en: '2. Generate your image' },
  main_view_wait_button: { pt: 'Aguarde', it: 'Attendi', en: 'Wait' },
  main_view_generate_button: { pt: 'Gerar Imagem', it: 'Genera Immagine', en: 'Generate Image' },
  main_view_pro_promo_title: { pt: 'Quer pular a espera e ter mais opções?', it: 'Vuoi saltare l\'attesa e avere più opzioni?', en: 'Want to skip the wait and have more options?' },
  main_view_pro_promo_subtitle: { pt: 'Acelere sua carreira de modelo agora mesmo!', it: 'Accelera la tua carriera di modello ora!', en: 'Accelerate your modeling career right now!' },
  main_view_pro_promo_button: { pt: 'Torne-se PRO!', it: 'Diventa PRO!', en: 'Become PRO!' },
  main_view_cooldown_message: { pt: 'Você pode gerar uma imagem a cada {0} minutos.', it: 'Puoi generare un\'immagine ogni {0} minuti.', en: 'You can generate an image every {0} minutes.' },
  community_title: { pt: 'Comunidade Top Model', it: 'Community Top Model', en: 'Top Model Community' },
  community_empty: { pt: 'A comunidade ainda está vazia. Seja o primeiro a criar uma imagem!', it: 'La community è ancora vuota. Sii il primo a creare un\'immagine!', en: 'The community is still empty. Be the first to create an image!' },
  community_use_style_button: { pt: 'Usar Estilo', it: 'Usa Stile', en: 'Use Style' },
  // Modal
  modal_use_style_button: { pt: '✨ Usar este Estilo', it: '✨ Usa questo Stile', en: '✨ Use this Style' },
  // Profile Screen
  profile_screen_title: { pt: 'Meu Perfil', it: 'Il Mio Profilo', en: 'My Profile' },
  profile_screen_change_selfie: { pt: 'Mudar Selfie (PRO)', it: 'Cambia Selfie (PRO)', en: 'Change Selfie (PRO)' },
  profile_screen_pro_title: { pt: 'Leve seu perfil ao próximo nível!', it: 'Porta il tuo profilo al livello successivo!', en: 'Take your profile to the next level!' },
  profile_screen_pro_desc: { pt: 'Com o plano PRO você pode mudar sua selfie e nome de usuário a qualquer momento, além de ter gerações ilimitadas.', it: 'Con il piano PRO puoi cambiare il tuo selfie e nome utente in qualsiasi momento, oltre ad avere generazioni illimitate.', en: 'With the PRO plan you can change your selfie and username at any time, plus have unlimited generations.' },
  profile_screen_pro_button: { pt: 'Ver Planos PRO', it: 'Vedi Piani PRO', en: 'View PRO Plans' },
  // Payment Screen (New)
  payment_screen_title: { pt: 'Torne-se PRO', it: 'Diventa PRO', en: 'Become PRO' },
  payment_screen_subtitle: { pt: 'Desbloqueie seu potencial máximo.', it: 'Sblocca il tuo potenziale massimo.', en: 'Unlock your full potential.' },
  payment_screen_price: { pt: 'R$ 29,90', it: '€ 5,99', en: '$ 5.99' },
  payment_screen_monthly: { pt: '/mês', it: '/mese', en: '/month' },
  payment_screen_features_title: { pt: 'O que você ganha:', it: 'Cosa ottieni:', en: 'What you get:' },
  payment_screen_feature1: { pt: 'Gerações ilimitadas (sem espera)', it: 'Generazioni illimitate (senza attesa)', en: 'Unlimited generations (no waiting)' },
  payment_screen_feature2: { pt: 'Qualidade de imagem superior (HD)', it: 'Qualità dell\'immagine superiore (HD)', en: 'Superior image quality (HD)' },
  payment_screen_feature3: { pt: 'Sem marca d\'água nas fotos', it: 'Nessun watermark sulle foto', en: 'No watermark on photos' },
  payment_screen_feature4: { pt: 'Acesso a estilos e poses exclusivas', it: 'Accesso a stili e pose esclusive', en: 'Access to exclusive styles and poses' },
  payment_screen_secure_payment: { pt: 'Pagamento 100% Seguro', it: 'Pagamento Sicuro al 100%', en: '100% Secure Payment' },
  payment_screen_select_method: { pt: 'Selecione a forma de pagamento', it: 'Seleziona il metodo di pagamento', en: 'Select payment method' },
  payment_screen_pix: { pt: 'Pix', it: 'Pix', en: 'Pix' },
  payment_screen_card: { pt: 'Cartão de Crédito/Débito', it: 'Carta di Credito/Debito', en: 'Credit/Debit Card' },
  payment_screen_paypal: { pt: 'PayPal', it: 'PayPal', en: 'PayPal' },
  payment_screen_pay_button: { pt: 'Pagar e Assinar', it: 'Paga e Abbonati', en: 'Pay and Subscribe' },
  // Info Screen
  info_screen_title: { pt: 'Informações', it: 'Informazioni', en: 'Information' },
  info_screen_what_is_title: { pt: 'O que é o {0}?', it: 'Cos\'è {0}?', en: 'What is {0}?' },
  info_screen_what_is_desc: { pt: '{0} é o seu estúdio de moda pessoal, alimentado por inteligência artificial. Transforme uma simples selfie em um portfólio de modelo profissional, experimentando estilos de grandes marcas e cenários deslumbrantes. É o primeiro passo para a sua carreira dos sonhos.', it: '{0} è il tuo studio di moda personale, alimentato da intelligenza artificiale. Trasforma un semplice selfie in un portfolio di modello professionale, sperimentando stili di grandi marchi e scenari mozzafiato. È il primo passo per la carriera dei tuoi sogni.', en: '{0} is your personal fashion studio, powered by artificial intelligence. Transform a simple selfie into a professional model portfolio, experimenting with styles from major brands and stunning settings. It is the first step towards your dream career.' },
  info_screen_faq_title: { pt: 'Perguntas Frequentes (FAQ)', it: 'Domande Frequenti (FAQ)', en: 'Frequently Asked Questions (FAQ)' },
  info_screen_faq1_q: { pt: 'Como a minha selfie é usada?', it: 'Come viene usato il mio selfie?', en: 'How is my selfie used?' },
  info_screen_faq1_a: { pt: 'Sua selfie é usada como base para o rosto do modelo nas fotos geradas. A IA integra seu rosto de forma realista nas poses e estilos que você escolher.', it: 'Il tuo selfie viene utilizzato come base per il volto del modello nelle foto generate. L\'IA integra il tuo volto in modo realistico nelle pose e negli stili che scegli.', en: 'Your selfie is used as the basis for the model\'s face in the generated photos. The AI realistically integrates your face into the poses and styles you choose.' },
  info_screen_faq2_q: { pt: 'Posso usar fotos de outras pessoas?', it: 'Posso usare foto di altre persone?', en: 'Can I use other people\'s photos?' },
  info_screen_faq2_a: { pt: 'Na versão gratuita, você só pode usar a selfie que tirou no cadastro. A versão PLUS permite que você faça upload de outras fotos.', it: 'Nella versione gratuita, puoi usare solo il selfie che hai scattato durante la registrazione. La versione PLUS ti permette di caricare altre foto.', en: 'In the free version, you can only use the selfie you took during registration. The PLUS version allows you to upload other photos.' },
  info_screen_faq3_q: { pt: 'As minhas imagens são privadas?', it: 'Le mie immagini sono private?', en: 'Are my images private?' },
  info_screen_faq3_a: { pt: 'As imagens que você gera aparecem na Community Feed por 7 dias, visíveis a outros usuários, como especificado nos Termos de Serviço.', it: 'Le immagini che generi appaiono nel Community Feed per 7 giorni, visibili ad altri utenti, come specificato nei Termini di Servizio.', en: 'The images you generate appear in the Community Feed for 7 days, visible to other users, as specified in the Terms of Service.' },
  info_screen_plans_title: { pt: 'Planos PLUS e PRO', it: 'Piani PLUS e PRO', en: 'PLUS and PRO Plans' },
  info_screen_plans_desc: { pt: 'Eleve sua experiência e acelere sua carreira com nossos planos:', it: 'Migliora la tua esperienza e accelera la tua carriera con i nostri piani:', en: 'Elevate your experience and accelerate your career with our plans:' },
  info_screen_plus_desc: { pt: 'Permite que você faça o upload de qualquer foto do seu dispositivo, dando mais liberdade criativa.', it: 'Ti permette di caricare qualsiasi foto dal tuo dispositivo, dandoti più libertà creativa.', en: 'Allows you to upload any photo from your device, giving you more creative freedom.' },
  info_screen_pro_desc: { pt: 'Gerações ilimitadas sem espera, qualidade superior (HD), sem marca d\'água e acesso a estilos e poses exclusivas.', it: 'Generazioni illimitate senza attesa, qualità superiore (HD), senza watermark e accesso a stili e pose esclusive.', en: 'Unlimited generations without waiting, superior quality (HD), no watermark, and access to exclusive styles and poses.' },
  info_screen_contact_title: { pt: 'Contatos e Redes Sociais', it: 'Contatti e Social Network', en: 'Contacts and Social Networks' },
  info_screen_contact_desc: { pt: 'Siga-nos e fique por dentro das novidades!', it: 'Seguici e resta aggiornato sulle novità!', en: 'Follow us and stay up to date with the news!' },
  info_screen_contact_email: { pt: 'Contato por E-mail', it: 'Contatto via E-mail', en: 'Contact by E-mail' },
  // Aria labels
  aria_info: { pt: 'Informações', it: 'Informazioni', en: 'Information' },
  aria_my_profile: { pt: 'Meu Perfil', it: 'Il Mio Profilo', en: 'My Profile' },
  aria_logout: { pt: 'Sair', it: 'Esci', en: 'Logout' },
  aria_user_selfie: { pt: 'Selfie do usuário', it: 'Selfie dell\'utente', en: 'User selfie' },
  aria_like_image: { pt: 'Gostar da imagem de {0}, atualmente {1} curtidas', it: 'Metti Mi Piace all\'immagine di {0}, attualmente {1} Mi Piace', en: 'Like image by {0}, currently {1} likes' },
  aria_generate_with_style: { pt: 'Gerar com este estilo', it: 'Genera con questo stile', en: 'Generate with this style' },
  aria_share_image: { pt: 'Compartilhar ou baixar imagem', it: 'Condividi o scarica immagine', en: 'Share or download image' },
  aria_close_modal: { pt: 'Fechar visualização da imagem', it: 'Chiudi visualizzazione immagine', en: 'Close image view' },
  // Alerts and Banners
  welcome_back: { pt: 'Bentornato, {0}!', it: 'Bentornato, {0}!', en: 'Welcome back, {0}!' },
  alert_whatsapp_thanks: { pt: 'Obrigado! Em breve você receberá novidades no WhatsApp: {0}. A função de upload foi liberada! (simulação)', it: 'Grazie! Presto riceverai notizie su WhatsApp: {0}. La funzione di upload è stata sbloccata! (simulazione)', en: 'Thank you! You will soon receive news on WhatsApp: {0}. The upload feature has been unlocked! (simulation)' },
  alert_payment_soon: { pt: 'Sistema de pagamento em breve!', it: 'Sistema di pagamento in arrivo!', en: 'Payment system coming soon!' },
  share_title: { pt: 'Top Model AI - Criação de @{0}', it: 'Top Model AI - Creazione di @{0}', en: 'Top Model AI - Creation by @{0}' },
  share_text: { pt: 'Olha que imagem incrível eu criei com o Top Model AI! Estilo: {0}', it: 'Guarda che immagine incredibile ho creato con Top Model AI! Stile: {0}', en: 'Look at this incredible image I created with Top Model AI! Style: {0}' },
  alert_share_failed: { pt: 'Não foi possível compartilhar a imagem. Iniciando o download.', it: 'Impossibile condividere l\'immagine. Avvio del download.', en: 'Could not share the image. Starting download.' },
  // Errors
  error_timeout_30s: { pt: 'A geração demorou muito (30s) e foi cancelada. Por favor, tente novamente.', it: 'La generazione ha impiegato troppo tempo (30s) ed è stata annullata. Riprova.', en: 'Generation took too long (30s) and was canceled. Please try again.' },
  error_connection: { pt: 'Erro de conexão. Verifique sua internet e tente novamente.', it: 'Errore di connessione. Controlla la tua connessione internet e riprova.', en: 'Connection error. Check your internet and try again.' },
  error_server_timeout: { pt: 'O servidor demorou muito para responder (IA muito ocupada). Por favor, tente novamente em alguns instantes.', it: 'Il server ha impiegato troppo tempo a rispondere (IA molto occupata). Riprova tra qualche istante.', en: 'The server took too long to respond (AI is very busy). Please try again in a few moments.' },
  error_unexpected_response: { pt: 'O servidor retornou uma resposta inesperada (status {0}). Tente novamente.', it: 'Il server ha restituito una risposta inaspettata (stato {0}). Riprova.', en: 'The server returned an unexpected response (status {0}). Please try again.' },
  error_server_status: { pt: 'Ocorreu um erro no servidor (status {0}).', it: 'Si è verificato un errore sul server (stato {0}).', en: 'An error occurred on the server (status {0}).' },
  error_no_image_in_response: { pt: 'A resposta do servidor foi bem-sucedida, mas não continha uma imagem.', it: 'La risposta del server è andata a buon fine, ma non conteneva un\'immagine.', en: 'The server response was successful, but it did not contain an image.' },
  error_incomplete_user_data: { pt: 'Erro: Dados do usuário incompletos.', it: 'Errore: Dati utente incompleti.', en: 'Error: Incomplete user data.' },
  error_unknown: { pt: 'Ocorreu um erro desconhecido.', it: 'Si è verificato un errore sconosciuto.', en: 'An unknown error occurred.' },
  error_google_internal: { pt: 'Ocorreu um erro interno no servidor de IA. Por favor, tente novamente.', it: 'Si è verificato un errore interno nel server AI. Per favore, riprova.', en: 'An internal error occurred on the AI server. Please try again.' },
  error_google_invalid_argument: { pt: 'Não foi possível processar a imagem de entrada. Tente tirar outra selfie.', it: 'Impossibile elaborare l\'immagine di input. Prova a scattare un altro selfie.', en: 'Unable to process the input image. Please try taking another selfie.' },
  // Style Names
  style_eclectic: { pt: 'Eclettico', it: 'Eclettico', en: 'Eclectic' },
  style_glamour: { pt: 'Glamour', it: 'Glamour', en: 'Glamour' },
  style_classic: { pt: 'Classico', it: 'Classico', en: 'Classic' },
  style_sporty: { pt: 'Sportivo', it: 'Sportivo', en: 'Sporty' },
  style_sicilian: { pt: 'Siciliano', it: 'Siciliano', en: 'Sicilian' },
  style_minimalist: { pt: 'Minimalista', it: 'Minimalista', en: 'Minimalist' },
};